import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Background from 'c/Background'
import { CategoryProvider } from 'context/CategoryContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Background numSections={15} />
        <div className='mx-auto max-w-screen-lg z-50 overflow-hidden'>
          <CategoryProvider>
            <div className='flex min-h-screen justify-center items-center p-24'>
              {children}
            </div>
          </CategoryProvider>
        </div>
      </body>
    </html>
  )
}
